name: Integration Tests

env:
  DB_HOST: "localhost"
  DB_USER: "postgres1"
  DB_PASSWORD: "root"
  DB_PORT: "5432"
  DB_DATABASE: "databasetwo"

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Updating Packages
        run: sudo apt-get update

      - name: Install PostgreSQL
        run: |
          sudo systemctl start postgresql
      
      - name: Create Database
        run: |
          sudo -u postgres psql -c "CREATE DATABASE $DB_DATABASE";
          sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_DATABASE TO $DB_USER";

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
