name: Integration

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install PostgreSQL
        run: |
          # Update package repositories and install PostgreSQL
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib

          # Start PostgreSQL service
          sudo systemctl start postgresql.service

          # Check PostgreSQL service status
          sudo systemctl status postgresql.service

          # Wait for PostgreSQL service to start
          sleep 10

          # Create database and user
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_DATABASE }};"
          sudo -u postgres psql -c "CREATE USER ${{ secrets.DB_USER }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DB_DATABASE }} TO ${{ secrets.DB_USER }};"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Print Working Directory
        run: pwd

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
