name: Integration

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_DATABASE }};"
          sudo -u postgres psql -c "CREATE USER ${{ secrets.DB_USER }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}'; GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DB_DATABASE }} TO ${{ secrets.DB_USER }};"
        
      - name: Modify pg_hba.conf
        run: |
          sudo sed -i "s/ident/md5/g" /var/lib/pgsql/data/pg_hba.conf
          
      - name: Restart PostgreSQL
        run: sudo systemctl restart postgresql

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Print Working Directory
        run: pwd

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
